feat: check secrets (#42)

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -82,13 +82,29 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Check DEPLOY_KEY Secret
+        if: inputs.useDeployKey
+        run: |
+          if [ -z "${{ secrets.DEPLOY_KEY }}" ]; then
+            echo "::error::Error: useDeployKey is true, but secrets.DEPLOY_KEY is missing"
+            exit 1
+          fi
+
       - name: Checkout w/ Deploy Key
         if: inputs.useDeployKey
         uses: actions/checkout@v5.0.0
         with:
           fetch-depth: 0
           ssh-key: ${{ secrets.DEPLOY_KEY }}
-      
+
+      - name: Check GH_PAT Secret
+        if: inputs.usePAT
+        run: |
+          if [ -z "${{ secrets.GH_PAT }}" ]; then
+            echo "::error::Error: usePAT is true, but secrets.GH_PAT is missing"
+            exit 1
+          fi
+
       - name: Checkout w/ PAT
         if: inputs.usePAT
         uses: actions/checkout@v5.0.0
